settings:
  legacy:
    force: false
    interval: 100ms
schema:
- name: api
  path: .
  commands:
    install:
      status: true
      method: go build -o /go/bin/app ./api/main.go
    run:
      status: true
      method: /go/bin/app
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
