// Code generated by MockGen. DO NOT EDIT.
// Source: monthly_work.go

// Package repository is a generated GoMock package.
package repository

import (
	gomock "github.com/golang/mock/gomock"
	model "influ-dojo/api/domain/model"
	reflect "reflect"
)

// MockMonthlyWork is a mock of MonthlyWork interface.
type MockMonthlyWork struct {
	ctrl     *gomock.Controller
	recorder *MockMonthlyWorkMockRecorder
}

// MockMonthlyWorkMockRecorder is the mock recorder for MockMonthlyWork.
type MockMonthlyWorkMockRecorder struct {
	mock *MockMonthlyWork
}

// NewMockMonthlyWork creates a new mock instance.
func NewMockMonthlyWork(ctrl *gomock.Controller) *MockMonthlyWork {
	mock := &MockMonthlyWork{ctrl: ctrl}
	mock.recorder = &MockMonthlyWorkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMonthlyWork) EXPECT() *MockMonthlyWorkMockRecorder {
	return m.recorder
}

// LoadTop3 mocks base method.
func (m *MockMonthlyWork) LoadTop3() ([]*model.Work, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadTop3")
	ret0, _ := ret[0].([]*model.Work)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadTop3 indicates an expected call of LoadTop3.
func (mr *MockMonthlyWorkMockRecorder) LoadTop3() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadTop3", reflect.TypeOf((*MockMonthlyWork)(nil).LoadTop3))
}

// LoadByScreenName mocks base method.
func (m *MockMonthlyWork) LoadByScreenName(screenName string) (*model.Work, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadByScreenName", screenName)
	ret0, _ := ret[0].(*model.Work)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadByScreenName indicates an expected call of LoadByScreenName.
func (mr *MockMonthlyWorkMockRecorder) LoadByScreenName(screenName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadByScreenName", reflect.TypeOf((*MockMonthlyWork)(nil).LoadByScreenName), screenName)
}

// Save mocks base method.
func (m *MockMonthlyWork) Save(work *model.Work) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", work)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockMonthlyWorkMockRecorder) Save(work interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockMonthlyWork)(nil).Save), work)
}
